spring.application.name=customer-service
server.port=8081

spring.datasource.url=jdbc:h2:mem:customers-db
spring.h2.console.enabled=true
# D�sactiver temporairement la recherche de config si vous n'avez pas encore de Config Server
spring.cloud.config.enabled=false

# Configuration Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.discovery.enabled=true

# Actuator : Exposer tous les points de contr�le (sant�, info, etc.)
management.endpoints.web.exposure.include=*
