spring.application.name=inventory-service
server.port=8082

# Désactiver temporairement la recherche de config si vous n'avez pas encore de Config Server
spring.cloud.config.enabled=false

# Configuration Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Actuator : Exposer tous les points de contrôle (santé, info, etc.)
management.endpoints.web.exposure.include=*