spring.application.name=eureka-service
server.port=8761

# Empêcher le serveur de chercher un autre serveur Eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Désactiver config server si non présent pour le moment
spring.cloud.config.enabled=false