spring.application.name=config-service
server.port=9999

# Utilisation du mode "native" (fichiers locaux) au lieu de Git pour commencer
spring.profiles.active=native
# Chemin vers le dossier où vous allez créer vos fichiers de config
# Sur Mac, créez un dossier dans votre projet (ex: src/main/resources/configurations)
spring.cloud.config.server.native.search-locations=classpath:/configurations

# Enregistrement sur Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/